baseurl: https://hugo-future-imperfect-slim.netlify.app/
DefaultContentLanguage: en
title: Hugo Future Imperfect Slim
theme: hugo-future-imperfect-slim
paginate: 3
disqusShortname: ''
googleAnalytics: ''
pluralizeListTitles: no
disableLanguages: []
markup:
  goldmark:
    renderer:
      unsafe: yes
module:
  hugoVersion:
    extended: yes
    min: 0.62.0
outputs:
  home:
    - html
    - json
    - rss
params:
  cssFiles: default
  enableCDN: no
  footer:
    rssFooter: yes
    socialFooter: yes
  header:
    dynamicTitles: yes
    languageMenu: yes
    navbarTitle: Future Imperfect
    searchMenu: yes
    shareMenu: yes
  hideEmptyStats: no
  highlightjs: yes
  highlightjsLang: []
  highlightjsTheme: ''
  imageStretch: ''
  intro:
    alwaysOnHomepage: no
    header: Hugo Future Imperfect Slim
    hideWhenSingleColumn: no
    paragraph: Another fine, responsive site template by <a href='http://html5up.net'>HTML5
      UP</a>.
    pic:
      alt: Hugo Future Imperfect Slim
      shape: circle
      src: img/main/logo.jpg
      width: ''
    rssIntro: yes
    socialIntro: yes
  jsFiles: default
  meta:
    author: HTML5UP and Hugo
    description: A theme by HTML5 UP, ported by Julio Pescador. Slimmed and enhanced
      by Patrick Collins. Multilingual by StatnMap. Powered by Hugo.
    favicon: no
    faviconVersion: '1'
    iOSColor: '#ffffff'
    msColor: '#ffffff'
    svg: yes
  readingTime: yes
  removeBlur: no
  sidebar:
    about: This theme was developed for Hugo static site generator.
    categories: yes
    categoriesByCount: yes
    postAmount: 5
  socialShare:
    - twitter
    - facebook
    - reddit
    - linkedin
    - pinterest
    - email
  staticman:
    api: ''
    branch: ''
    enabled: yes
    gitProvider: ''
    recaptcha:
      encryptedKey: ''
      siteKey: ''
    repo: ''
    username: ''
  utterances:
    enabled: no
    issueNumber: ''
    issueTerm: pathname
    label: ''
    repo: ''
    theme: github-light
  viewMorePostsLink: blog
menu:
  main:
    - identifier: home
      name: Home
      pre: <i class='fa fa-home'></i>
      url: ''
      weight: 1
    - identifier: about
      name: About
      pre: <i class='far fa-id-card'></i>
      url: about
      weight: 2
    - identifier: blog
      name: Blog
      pre: <i class='far fa-newspaper'></i>
      url: blog
      weight: 3
    - identifier: categories
      name: Categories
      pre: <i class='fas fa-sitemap'></i>
      url: categories
      weight: 5
    - identifier: contact
      name: Contact
      pre: <i class='far fa-envelope'></i>
      url: contact
      weight: 6
Languages:
  de:
    LanguageCode: de
    LanguageName: Deutsche
    weight: 5
  en:
    LanguageCode: en
    LanguageName: English
    weight: 1
  es:
    LanguageCode: es
    LanguageName: Española
    weight: 6
  fr:
    LanguageCode: fr
    LanguageName: Français
    description: Un thème par HTML5 UP, porté par Julio Pescador. Simplifié et amélioré
      par Patrick Collins. Multilingue par StatnMap. Propulsé par Hugo.
    menu:
      main:
        - identifier: home
          name: Accueil
          pre: <i class='fas fa-home'></i>
          url: ''
          weight: 1
        - identifier: about
          name: A Propos
          pre: <i class='far fa-id-card'></i>
          url: about
          weight: 2
        - identifier: blog
          name: Blog
          pre: <i class='far fa-newspaper'></i>
          url: blog
          weight: 3
        - identifier: categories
          name: Catégories
          pre: <i class='fas fa-sitemap'></i>
          url: categories
          weight: 5
        - identifier: contact
          name: Contact
          pre: <i class='far fa-envelope'></i>
          url: contact
          weight: 6
    title: Hugo Future Imperfect Slim en français
    weight: 2
  ja:
    LanguageCode: ja
    LanguageName: 日本語
    weight: 9
  nl:
    LanguageCode: nl
    LanguageName: Nederlands
    menu:
      main:
        - identifier: home
          name: Home
          pre: <i class='fas fa-home'></i>
          url: ''
          weight: 1
        - identifier: about
          name: Over
          pre: <i class='far fa-id-card'></i>
          url: about
          weight: 2
        - identifier: blog
          name: Blog
          pre: <i class='far fa-newspaper'></i>
          url: blog
          weight: 3
        - identifier: categories
          name: Categorieën
          pre: <i class='fas fa-sitemap'></i>
          url: categories
          weight: 5
        - identifier: contact
          name: Contact
          pre: <i class='far fa-envelope'></i>
          url: contact
          weight: 6
    weight: 10
  pl:
    LanguageCode: pl
    LanguageName: Polski
    description: Motyw HTML5 UP, przeniesiony przez Julio Pescadora i wzbogacony przez
      Patricka Collinsa. Wielojęzyczny przez StatnMap. Zasilany przez Hugo.
    menu:
      main:
        - identifier: home
          name: Home
          pre: <i class='fas fa-home'></i>
          url: ''
          weight: 1
        - identifier: about
          name: O mnie
          pre: <i class='far fa-id-card'></i>
          url: about
          weight: 2
        - identifier: blog
          name: Blog
          pre: <i class='far fa-newspaper'></i>
          url: blog
          weight: 3
        - identifier: categories
          name: Kategorie
          pre: <i class='fas fa-sitemap'></i>
          url: categories
          weight: 5
        - identifier: contact
          name: Kontakt
          pre: <i class='far fa-envelope'></i>
          url: contact
          weight: 6
    title: Hugo Future Imperfect Slim po polsku
    weight: 2
  pt:
    LanguageCode: pt
    LanguageName: Português
    description: Um tema do HTML5 UP, portado por Julio Pescadora e reduzido por Patrick
      Collins. Multilíngue por StatnMap. Feito com Hugo.
    menu:
      main:
        - identifier: home
          name: Início
          pre: <i class='fas fa-home'></i>
          url: ''
          weight: 1
        - identifier: about
          name: Sobre
          pre: <i class='far fa-id-card'></i>
          url: about
          weight: 2
        - identifier: blog
          name: Blog
          pre: <i class='far fa-newspaper'></i>
          url: blog
          weight: 3
        - identifier: categories
          name: Categorias
          pre: <i class='fas fa-sitemap'></i>
          url: categories
          weight: 5
        - identifier: contact
          name: Contato
          pre: <i class='far fa-envelope'></i>
          url: contact
          weight: 6
    title: Hugo Future Imperfect Slim em português
    weight: 4
  zh-CN:
    LanguageCode: zh-CN
    LanguageName: 中文 (简体)
    weight: 7
  zh-TW:
    LanguageCode: zh-TW
    LanguageName: 中文 (正體)
    weight: 8
social:
  behance: ''
  bitbucket: ''
  codepen: ''
  deviantart: ''
  dribbble: ''
  email: example
  facebook: example
  flickr: example
  foursquare: ''
  github: pacollins/hugo-future-imperfect-slim
  gitlab: ''
  googleplus: ''
  googlescholar: ''
  instagram: example
  jsfiddle: ''
  keybase: example
  linkedin: example
  linkedin_company: examplebusiness
  mastodon: example.com/@example
  medium: ''
  orcid: ''
  pinterest: example
  qq: ''
  quora: ''
  reddit: example
  researchgate: example
  skype: ''
  slideshare: ''
  snapchat: ''
  stackoverflow: ''
  strava: ''
  telegram: example
  tumblr: ''
  twitter: example
  vimeo: ''
  vine: ''
  wechat: ''
  whatsapp: ''
  wordpress: ''
  xing: ''
  youtube: ''
